# -*- coding: utf-8 -*-
from . import omni_partner_identity
from . import omni_webhook_event
from . import omni_integration
from . import omni_stage_event
from . import omni_promo
from . import res_partner
from . import mail_channel
from . import mail_guest
from . import mail_message
from . import omni_bridge
from . import omni_sales_intel
from . import product_template
from . import omni_knowledge
from . import omni_memory
from . import omni_ai
from . import omni_ai_job
from . import omni_notify
from . import omni_crm_analytics
from . import omni_tg_broadcast
from . import res_config_settings
from . import omni_coupon_redemption
from . import sale_order
from . import payment_transaction
from . import account_move
