# -*- coding: utf-8 -*-
{
    'name': 'Omnichannel Bridge',
    'summary': 'Aggregate messengers into Discuss; webhooks, CRM partner match, AI/sales hooks',
    'version': '17.0.1.0.0',
    'category': 'Productivity/Discuss',
    'author': 'Fajna',
    'license': 'LGPL-3',
    'depends': [
        'base_setup',
        'mail',
        'crm',
        'sale_management',
        'stock',
        'account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/omni_defaults.xml',
        'data/omni_ai_job_cron.xml',
        'views/omni_integration_views.xml',
        'views/omni_promo_views.xml',
        'views/omni_insurance_package_views.xml',
        'views/omni_legal_document_views.xml',
        'views/omni_prompt_audit_views.xml',
        'views/omni_stage_event_views.xml',
        'views/omni_stage_transition_views.xml',
        'views/omni_objection_policy_views.xml',
        'views/omni_moderation_rule_views.xml',
        'views/omni_knowledge_article_views.xml',
        'views/omni_outbound_log_views.xml',
        'views/omni_payment_event_views.xml',
        'views/omni_manager_reply_views.xml',
        'views/res_config_settings_views.xml',
        'views/mail_channel_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/omni_crm_analytics_views.xml',
        'views/omni_tg_broadcast_views.xml',
        'views/omni_reserve_entry_views.xml',
        'views/omni_ops_views.xml',
    ],
    'external_dependencies': {
        'python': ['requests', 'pytz'],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
