#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build data/omni_camp_knowledge_articles.xml from the sibling `camp` repo
knowledge-base (markdown). Re-run after camp cards change, then commit XML.

Usage (from omnichannel-bridge repo root):
  python3 scripts/generate_camp_knowledge_data.py

Override camp root:
  CAMP_KNOWLEDGE_BASE=/path/to/camp/knowledge-base python3 scripts/generate_camp_knowledge_data.py
"""
from __future__ import annotations

import os
import re
import xml.sax.saxutils as saxutils
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CAMP_KB = REPO_ROOT.parent / 'camp' / 'knowledge-base'
OUT_PATH = REPO_ROOT / 'addons' / 'omnichannel_bridge' / 'data' / 'omni_camp_knowledge_articles.xml'

MAX_BODY = 12000  # keep XML manageable; RAG still matches on name + start of body


def _strip_md_fences(text: str) -> str:
    text = re.sub(r'```css.*?```', ' ', text, flags=re.S | re.I)
    text = re.sub(r'```javascript.*?```', ' ', text, flags=re.S | re.I)
    text = re.sub(r'```[a-z]*\n.*?```', ' ', text, flags=re.S | re.I)
    return text


def _flatten_md(text: str) -> str:
    text = _strip_md_fences(text)
    text = re.sub(r'^#{1,6}\s+', '\n', text, flags=re.M)
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def _cdata(body: str) -> str:
    """Safe CDATA embedding."""
    return '<![CDATA[' + body.replace(']]>', ']]]]><![CDATA[>') + ']]>'


def _xml_id_from_stem(stem: str) -> str:
    s = re.sub(r'[^a-zA-Z0-9]+', '_', stem).strip('_').lower()
    return f'omni_kb_{s}'[:80]


def _record(
    xml_id: str,
    name: str,
    body: str,
    priority: int,
    category: str = 'faq',
    *,
    source_type: str | None = None,
    source_url: str | None = None,
) -> str:
    body = _flatten_md(body)[:MAX_BODY]
    extra = ''
    if source_type:
        extra += f'        <field name="source_type">{source_type}</field>\n'
    if source_url:
        extra += f'        <field name="source_url">{saxutils.escape(source_url)}</field>\n'
    return f'''    <record id="{xml_id}" model="omni.knowledge.article">
        <field name="name">{saxutils.escape(name)}</field>
        <field name="category">{category}</field>
        <field name="channel_scope">all</field>
        <field name="priority" eval="{priority}"/>
        <field name="active" eval="True"/>
{extra}        <field name="body">{_cdata(body)}</field>
    </record>
'''


def main() -> None:
    kb = Path(os.environ.get('CAMP_KNOWLEDGE_BASE', str(DEFAULT_CAMP_KB))).resolve()
    if not kb.is_dir():
        raise SystemExit(f'Camp knowledge-base not found: {kb}')

    blocks: list[str] = []
    blocks.append('<?xml version="1.0" encoding="utf-8"?>')
    blocks.append('<odoo noupdate="1">')
    blocks.append(
        '    <!-- Generated by scripts/generate_camp_knowledge_data.py — do not hand-edit blindly -->'
    )

    static_sources = [
        (
            '00_company.md',
            'CampScout: компанія, реквізити та офіційний статус',
            3,
            'policy',
        ),
        (
            '00_faq_common.md',
            'CampScout: загальні FAQ для батьків',
            6,
            'faq',
        ),
        (
            '00_addons.md',
            'CampScout: додаткові продукти та послуги',
            8,
            'faq',
        ),
        (
            '00_insurance.md',
            'CampScout: страхування та гарантія невиїзду',
            9,
            'insurance',
        ),
        (
            '00_contract.md',
            'CampScout: умови договору та повернення',
            10,
            'policy',
        ),
        (
            '00_rodo.md',
            'CampScout: RODO і обробка персональних даних',
            11,
            'policy',
        ),
        (
            '00_cookie-policy.md',
            'CampScout: політика cookie',
            13,
            'policy',
            'policy_doc',
            'https://campscout.eu/cookie-policy',
        ),
        (
            '00_child-protection-policy.md',
            'CampScout: політика захисту дітей',
            14,
            'policy',
            'policy_doc',
            'https://campscout.eu/child-protection',
        ),
    ]
    for item in static_sources:
        rel_path = item[0]
        title = item[1]
        priority = item[2]
        category = item[3]
        kw = {}
        if len(item) >= 6:
            kw['source_type'] = item[4]
            kw['source_url'] = item[5]
        src = kb / rel_path
        if src.is_file():
            blocks.append(
                _record(
                    _xml_id_from_stem(rel_path),
                    title,
                    src.read_text(encoding='utf-8'),
                    priority=priority,
                    category=category,
                    **kw,
                )
            )

    schedule = kb / '00_schedule.md'
    if schedule.is_file():
        blocks.append(
            _record(
                'omni_kb_camp_schedule_day',
                'CampScout: рамковий розклад дня та харчування',
                schedule.read_text(encoding='utf-8'),
                priority=5,
                category='policy',
            )
        )

    camp_types = kb / '00_camp_types.md'
    if camp_types.is_file():
        blocks.append(
            _record(
                'omni_kb_camp_types_overview',
                'CampScout: типи таборів (огляд)',
                camp_types.read_text(encoding='utf-8'),
                priority=12,
                category='policy',
            )
        )

    camps_dir = kb / 'camps'
    if camps_dir.is_dir():
        for path in sorted(camps_dir.glob('*.md')):
            raw = path.read_text(encoding='utf-8')
            title_m = re.search(r'^#\s+(.+)$', raw, re.M)
            title = title_m.group(1).strip() if title_m else path.stem.replace('_', ' ')
            xml_id = _xml_id_from_stem(f'camp_{path.stem}')
            # Slightly spread priorities so ordering is stable between camps
            pri = 20 + (hash(path.stem) % 7)
            blocks.append(_record(xml_id, f'Табір: {title}', raw, priority=pri))

    blocks.append('</odoo>')
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text('\n'.join(blocks) + '\n', encoding='utf-8')
    print(f'Wrote {OUT_PATH} ({len(blocks) - 4} records)')


if __name__ == '__main__':
    main()
